<?php

namespace webd\structures;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-21 at 11:46:41.
 */
class KDTreeTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var KDTree
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $points = array(
            new \webd\vectors\Vector(1, 2, 3),
            new \webd\vectors\Vector(2, 3, 4),
            new \webd\vectors\Vector(3, 2, 5),
            new \webd\vectors\Vector(4, 1, 0)
        );
        $this->object = new KDTree($points);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testGetPoint() {
        $this->assertEquals(
                array(3,2,5),
                $this->object->getPoint()->getValue()
        );
    }

}
